## This file contain various NumPy exercises and their solutions.  It is intended for practice and learning purposes.

In [2]:
import numpy 
import numpy as np

### 1. Create a 1D NumPy array of integers from 0 to 9.

In [3]:
arr = numpy.array([0,1,2,3,4,5,6,7,8,9])
arr_2 = np.array([0,1,2,3,4,5,6,7,8,9])


print(arr)
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(type(arr))
print(type(arr_2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 2. Transform a list, a tuple, and a set into NumPy arrays.

In [5]:
ex_list = [1,2,3]
ex_tuple = ("a","b","c")
ex_set = {1.5, 4.33, 6.292}

print(type(ex_list),type(ex_tuple),type(ex_set), sep='  ')
print(ex_list,ex_tuple,ex_set, sep='  ')
print('\n')

new_list = np.array(ex_list)
new_tuple = np.array(ex_tuple)
new_set = np.array(ex_set)

print(type(new_list),type(new_tuple),type(new_set), sep='  ')
print(new_list,new_tuple,new_set)





<class 'list'>  <class 'tuple'>  <class 'set'>
[1, 2, 3]  ('a', 'b', 'c')  {1.5, 4.33, 6.292}


<class 'numpy.ndarray'>  <class 'numpy.ndarray'>  <class 'numpy.ndarray'>
[1 2 3] ['a' 'b' 'c'] {1.5, 4.33, 6.292}


### 3. Create a 0D array (scalar), a 1D array (vector) a 2D array (matrix) a 3D array (tensor).

In [6]:
zero_dim = np.array(13)
one_dim = np.array([12,88])
two_dim = np.array([[12,44,16],[25,88,32]])
three_dim = np.array([[[10,40],[33,63]],[[40,10],[63,33]]])

# check on the dimension of the arrays usign '.ndim'

print(zero_dim.ndim, one_dim.ndim, two_dim.ndim, three_dim.ndim)

0 1 2 3


#### 4. Convert the 2D array above to a 3D array. Use the reshape method.

In [7]:
new_two_dim = two_dim.reshape(2,1,3)
print(two_dim)
print("\n")
print(new_two_dim)

[[12 44 16]
 [25 88 32]]


[[[12 44 16]]

 [[25 88 32]]]


#### 5. Find the memory size of the 2D array above. Use the nbytes attribute.

In [8]:
print(two_dim.nbytes)

print(new_two_dim.nbytes)

24
24


#### 6. Create a 4X4 array of random integers. Print the first 2 rows and the last 2 columns.

In [29]:
matrix = np.random.randint(0,20, size=(4,4))

print(matrix)


print(f"First two rows:\n", matrix[0:2])

print(f"Last two columns:\n",matrix[:,-2:])



[[10 13 18 14]
 [12 11 18 15]
 [10 19  5 10]
 [ 9  8 11 17]]
First two rows:
 [[10 13 18 14]
 [12 11 18 15]]
Last two columns:
 [[18 14]
 [18 15]
 [ 5 10]
 [11 17]]


#### 7. Create a 5X5 array of random floats. Extract an array of elements from odd rows and even columns from it.

In [44]:
big_m = np.random.randint(0,20, size=(5,5))
print(big_m, f'\n')

small_m = big_m[1::2,0::2]
print(small_m)

[[13  5  8  7 13]
 [14 10  1  6 11]
 [ 6 11 12 16 17]
 [ 3 15  1 10 16]
 [ 2 19  8 12  5]] 

[[14  1 11]
 [ 3  1 16]]


#### 8. Stack two arrays vertically and horizontally. Use the vstack and hstack functions.

In [70]:
first_vec = np.random.randint(0,10, size=(3))
sec_vec = np.random.randint(0,10, size=(3))

print(first_vec, sec_vec, f'\n')

vertical = np.vstack((first_vec,sec_vec))

print(vertical, f"\nDimension: {vertical.ndim}\n")

horizontal = np.hstack((first_vec,sec_vec))
print(horizontal,f"\nDimension: {horizontal.ndim}")


[6 8 3] [9 4 7] 

[[6 8 3]
 [9 4 7]] 
Dimension: 2

[6 8 3 9 4 7] 
Dimension: 1


#### 9. Replace all odd numbers in an array with -1.

In [100]:
array_init = np.random.randint(0,10, size=(3,3,2))

array_mod = array_init.copy()

array_mod[array_mod % 2 == 1] = -1

print(array_init)
print(f'\n')
print(array_mod)

[[[3 3]
  [3 6]
  [5 7]]

 [[9 9]
  [6 1]
  [5 4]]

 [[4 0]
  [5 0]
  [6 5]]]


[[[-1 -1]
  [-1  6]
  [-1 -1]]

 [[-1 -1]
  [ 6 -1]
  [-1  4]]

 [[ 4  0]
  [-1  0]
  [ 6 -1]]]


#### 10. Find the index of non-zero elements in an array. 

In [119]:
arr_ag = np.array([[[0,5,1],[2,0,3]],[[3,7,7,],[4,0,3]]])
print(arr_ag)

nzero_idx = np.nonzero(arr_ag)

print(nzero_idx)

[[[0 5 1]
  [2 0 3]]

 [[3 7 7]
  [4 0 3]]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 1, 0, 0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2, 0, 1, 2, 0, 2], dtype=int64))


#### 11. Find the intersection of two arrays. 

In [145]:
arr_one = np.array([2,4,3,7,5,8])
arr_two = np.random.randint(0,9, size=(6))

inter = np.intersect1d(arr_one, arr_two)
print(arr_one)
print(arr_two)

print(inter)

[2 4 3 7 5 8]
[0 6 2 1 6 5]
[2 5]


#### 12. Find the union of two arrays. Use the union1d function.

In [146]:
arr_one = np.random.randint(0,9, size=(6))
arr_two = np.random.randint(0,9, size=(6))

union = np.union1d(arr_one, arr_two)
print(arr_one)
print(arr_two)

print(union)



[6 8 5 0 7 1]
[0 8 2 1 8 8]
[0 1 2 5 6 7 8]
