## This file contain various NumPy exercises and their solutions.  It is intended for practice and learning purposes.

In [1]:
import numpy 
import numpy as np

### 1. Create a 1D NumPy array of integers from 0 to 9.

In [ ]:
arr = numpy.array([0,1,2,3,4,5,6,7,8,9])
arr_2 = np.array([0,1,2,3,4,5,6,7,8,9])


print(arr)
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(type(arr))
print(type(arr_2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 2. Transform a list, a tuple, and a set into NumPy arrays.

In [35]:
ex_list = [1,2,3]
ex_tuple = ("a","b","c")
ex_set = {1.5, 4.33, 6.292}

print(type(ex_list),type(ex_tuple),type(ex_set), sep='  ')
print(ex_list,ex_tuple,ex_set, sep='  ')
print('\n')

new_list = np.array(ex_list)
new_tuple = np.array(ex_tuple)
new_set = np.array(ex_set)

print(type(new_list),type(new_tuple),type(new_set), sep='  ')
print(new_list,new_tuple,new_set)





<class 'list'>  <class 'tuple'>  <class 'set'>
[1, 2, 3]  ('a', 'b', 'c')  {1.5, 4.33, 6.292}


<class 'numpy.ndarray'>  <class 'numpy.ndarray'>  <class 'numpy.ndarray'>
[1 2 3] ['a' 'b' 'c'] {1.5, 4.33, 6.292}
